version: "3.8"

services:
  web:
    image: gif_convertor_image
    ports:
      - "4200:4200"
      - "3000:3000"
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: workers/Dockerfile
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
    attachable: true
